# Generated by Django 5.0 on 2024-02-05 17:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_category_service_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Service",
            new_name="Doctors",
        ),
        migrations.AlterModelOptions(
            name="doctors",
            options={"verbose_name": "Врач", "verbose_name_plural": "Врачи"},
        ),
    ]
